### ISSUE TITLE
Add .tgz files to GitHub releases

### ISSUE THREAD

**Issue by anonymous2585** [microsoft/VisualProfiler-Unity#29]
## Describe the problem

This package doesn't have the .tgz package file in the GitHub releases as for the [MRTK relseases](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/releases).
The computer I work on doesn't have internet access, so I can't install the package using the git link in package manager. I had to manually download the code, pack it into a .tgz file and add it to my project.

## Describe the solution you'd like

I'd like to have an official .tgz file on GitHub releases so it's easy to download it and transfert it to an offline computer.

## Describe alternatives you've considered

Maybe it can also be released in the [Mixed Reality Feature Tool](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)?

**Comment by Cameron-Micka** [comment]
This is great feedback, we can start adding tgz files to our releases. @shaynie what do you think about adding this package to the [Mixed Reality Feature Tool](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool)?

**Comment by Cameron-Micka** [comment]
Added to our latest (and first official) release: https://github.com/microsoft/VisualProfiler-Unity/releases/tag/v3.3.0

**Comment by anonymous2585** [comment]
Perfect, thank you for this 🙂
Just don't forget to this this for all futur release 😉
