### ISSUE TITLE
How to Increase Font Resolution When Project Quality Is Set to Very Low

### ISSUE THREAD

**Issue by coltonix** [microsoft/VisualProfiler-Unity#31]
## The Issue
Texts on the profiler becomes highly blurry and illegible when the project quality is set to _Very Low_.

## A Potential Solution
All I did was 

1. First make a copy of the original immutable _Microsoft Mixed Reality Visual Profiler/Data_ folder to be able to edit the font file,
2. Reassign the new font texture and material to the Visual Profiler script component,
3. Navigate to the new /Data/Font, and on the Inspector change **Texture Type** to _Sprite (2D and UI)_ and then hit _apply_.
4. (Also make sure the Font texture's Max Size is not smaller than 512.)

I am hoping this would be made a little simpler to accomplish.

## Existing doc link
The issue is not mentioned in the existing doc.

## Additional context
If it matters at all, I am using
Unity 2021.3 LTS
MRTK 3
com.microsoft.mixedreality.visualprofiler#v3.3.0

Thanks for reading!

**Comment by Cameron-Micka** [comment]
Hi @coltonix, thanks for reporting this and providing a solution! I will make sure this is addressed in a future release.
