### ISSUE TITLE
Add screen-space options, and/or options to work with Orthographic cameras

### ISSUE THREAD

**Issue by xwipeoutx** [microsoft/VisualProfiler-Unity#35]
## Describe the problem

I want to use this for apps in screen-space, as well as immersive versions.  I'd be able to make do with world-space, except some of our apps also use orthographic cameras

## Describe the solution you'd like

An toggle in Window Settings to show this in screen-space, where it basically snaps to the anchor positions with the offsets given and stays there.  Ideally sitting on top of UI elements too

## Describe alternatives you've considered

I did try to just deal with it just being in world-space, but ran into issues with orthographic cameras (calculations obviously don't work, scale limit is much too small), clipping, and overlapping with the UI elements.

## Additional context

May be an odd request, but apps like Microsoft Mesh are a prime example of something that exists in both 2D and 3D space, and it's nice to have the same sort of profiler for simplicity.

I know I could use another profiler, but I just love this one so much ^_^.

I am having a play with hacking the shader a bit when orthographic, dunno how i'll go though.

**Comment by Cameron-Micka** [comment]
Hey Steve, thanks for the suggestion! You are absolutely right this would benefit apps which have orthographic cameras (like [Mesh](https://learn.microsoft.com/en-us/mesh/develop/debug-and-optimize-performance/performance-guidelines#performance-profiler)). We'll certainly put it on the todo list. Or, if you make progress on this don't hesitate to open a PR.
