### ISSUE TITLE
CPU Timestamps Don't Always Represent Frames Missed

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/VisualProfiler-Unity#4]
CPU timestamps may not always paint an accurate picture of missed frames in Unity. To gain a more accurate representation of missed presentations we should integrate [this API for UWP apps](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicframepresentationreport ).

**Comment by david-c-kline** [comment]
@Cameron-Micka , when you get this change implemented, we should apply it to the version in the [Mixed Reality Toolkit](https://github.com/Microsoft/MixedRealityToolkit-Unity) as well.

I'll work with you on that.

**Comment by Cameron-Micka** [comment]
@davidkline-ms I agree! That sounds perfect, I will let you know.
